version: '3'

services:

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    container_name: db_postgres_12
    env_file:
      - ./.env.dev

  drf:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash run.sh
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/supp_app_drf_v2
    ports:
      - '8000:8000'
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis_sa
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  celery:
    build:
      context: .
    container_name: celery_sa
    entrypoint: celery
    command: -A supp_app_drf_v2 worker -l info
    env_file:
      - ./.env.dev
    volumes:
     - .:/usr/src/supp_app_drf_v2
    links:
     - redis
    depends_on:
     - redis

  celery-beat:
    build: .
    container_name: celery_beat_sa
    command: celery -A supp_app_drf_v2 beat -l info
    volumes:
      - .:/usr/src/supp_app_drf_v2
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - celery

volumes:
  pg_data:
  redisdata: